name: Docker Image CI

#on:
on:
  push:
    tags:
      - 'v*.*.*'
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Test
      run: |
        echo $RELEASE_VERSION
        echo ${{ env.RELEASE_VERSION }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag mhmn/db-backup-scheduler:${{ env.RELEASE_VERSION }}
    - name: Push Docker image
      run: docker push mhmn/db-backup-scheduler:${{ env.RELEASE_VERSION }}
      
      
